spring:
  datasource:
    url: jdbc:mysql://152.136.33.217:3306/gym
    username: root
    password: yiqizou89.
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 1003

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.milotnt.pojo